= Null is ...


pass:[<span style="color: maroon;font-weight: bold;font-style: italic;font-size: 100px;">the bane of code management</span>]

== Question - How can nulls be managed in code?
* Manageable in smaller code snippets
* Becomes unmanageable as the code base grows -
** Unpredictable null flow
** Multiple channels - malformed data, network connectivity issues, service failures, thread deadlocks
** Uncertainity increases exponentially with the increasing codebase
** `return user.getAddress().getCity()` - user could be null, getAddress() could be null, or getCity() could be null, in which case.. the progam doesn't fail immediately, but when the calling code calls something on getCity()'s return value. +
*~Java~&nbsp;~14~&nbsp;~addressed~&nbsp;~this~&nbsp;~with~&nbsp;~Helpful~&nbsp;~NPE~*
** Modifying existing code base with null checks for every single instance - not feasible
** Legacy code can't use newer features, such as Optional, or pattern matching
** Libraries and services can't modify their public APIs and so they might not be able to use some of the safeguards

'''

[caption=" ", .center, cols="<40%, ^20%, >40%", width=95%, grid=none, frame=none]
|===
| link:21_ProblemStatementScale.adoc[◀️ Problem of Scale]
| link:Agenda.adoc[Agenda 🔼]
| link:23_ProblemStatementCodeManagement.adoc[Problem of Code Management ▶️]
|===
